import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AnnouncementBanner from "@/components/firstSection/AnnouncementBanner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Royale House",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <AnnouncementBanner />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
